title: Robot Antenna
hero_image: images/banner.png
description: Make your own robot with a blinking antenna
original_url: https://raspberrypi.org/learning/robot-antenna
theme: blue
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
interests: robots
technologies: physical computing, scratch
site_areas: ''
steps:
- title: Introduction
- title: What you will need
- title: Make an antenna
- title: Connect your antenna
- title: Make the antenna flash with code
- title: Make a cardboard robot
- title: "Challenge: beeps and flashes"
